### ISSUE TITLE
Dockerfile should use `&&` instead of `;` in Dockerfile RUN commands

### ISSUE THREAD

**Issue by andreiashu** [tiredofit/docker-alpine#1]
The use of `;` to separate commands will lead to errors not being propagated to the Docker process and therefore broken images. The solution is to use `&&` instead which will exit with code 1 immediately as a command returns a non-0 exit code.

For example:
```
[...]
### S6 Installation
       curl -sSL https://github.com/just-containers/s6-overlay/releases/download/${S6_OVERLAY_VERSION}/s6-overlay-amd64.tar.gz | tar xfz - -C / ; \
   
### Add Folders
       mkdir -p /assets/cron
[...]
```
In the above command, even if the network is down (and curl fails with exit code 1) the image will be built and tagged successfully becasue `mkdir -p /assets/cron` will signal an exit code of 0 to the Docker process.

This is very bad especially for CI environment but also local builds since people might not see the log output.

to test this you can do:
```
# this will incorrectly return code 0
false; true
echo $?

# this will correctly return code 1
false && true
echo $?
```

**Comment by tiredofit** [comment]
Hi there, you are very right. A couple months ago I switched over to the `; \` in an attempt to resolve some Docker build barking errors, and have neglected to move it back. I have a small addition that I need to add to the images in relation to msmtp on my private images and once tested will push them up to this repo which allows for proper fails when building.

**Comment by tiredofit** [comment]
Updated!
