### ISSUE TITLE
 How to build the ZABBIX server?

### ISSUE THREAD

**Issue by ppabc** [tiredofit/docker-alpine#3]
How to build the zabbix server?
Why use the zabbix client passive way?

**Comment by tiredofit** [comment]
The Zabbix server is seperate, this is just a base image that is used for my many other images. I don't believe I've posted my Zabbix image up on Github and left it private only. I've just created this repo https://github.com/tiredofit/docker-zabbix and will upload within the hour, however Docuementation will take longer to put together.
The Zabbix client can be used in passive / active mode depending on your configuration. I've provided a config that works well in our environment (600+ containers).

**Comment by tiredofit** [comment]
I've just posted the Dockerfiles and they are building on the Docker Hub. Setting it up in a 100% Dockerized environment brings it's challenges but certainly possible. Enjoy!

**Comment by ppabc** [comment]
Thank you
awesome!very useful and interesting!
