### ISSUE TITLE
UTC probably a more appropriate default timezone

### ISSUE THREAD

**Issue by stephenmoloney** [tiredofit/docker-alpine#4]
Since this image is used downstream by various others, it was rather hidden what the timezone would be until referring to this repository.

`Etc/UTC` seems like a reasonable timezone as default

**Comment by tiredofit** [comment]
You are right, makes much more sense.  These are copies of our internal images with a few features stripped out for sharing with the public. I've altered each to utilize UTC going forward for usage on the Docker Hub.
