### ISSUE TITLE
Image and any packages using this image fail to pull on LXC Containers.

### ISSUE THREAD

**Issue by mariaWitch** [tiredofit/docker-alpine#59]
### Summary
Whenever the image is pulled down from Docker hub or a package using this image is pulled, the following error is encountered when trying to pull the image:
`failed to register layer: ApplyLayer exit status 1 stdout:  stderr: lchown /run/fail2ban: invalid argument
`
Most of my reading into this, implies that this is an issue with rootless mode specifically. All of the other containers I was pulling did not have any issues, this was the only one that had any issues in rootless mode. Something during the pull is calling a UID and GID value beyond 65536, which is the max uid and gid values on an LXC container in rootless mode.

### Steps to reproduce

1. Attempt to pull the docker image from hub.docker.com on an LXC Container with Docker on it. (I have tried it on both Debian and Almalinux with the same results)

### What is the expected *correct* behavior?

The image should pull without erroring out.

### Relevant logs and/or screenshots

```
[root@docker3 ~]# docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.8.2-docker)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 4
 Server Version: 20.10.17
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
  userxattr: true
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 0197261a30bf81f1ee8e6a4dd2dea0ef95d67ccb
 runc version: v1.1.3-0-g6724737
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.15.30-2-pve
 Operating System: AlmaLinux 8.6 (Sky Tiger)
 OSType: linux
 Architecture: x86_64
 CPUs: 3
 Total Memory: 3.023GiB
 Name: docker3
 ID: SAV4:CK4E:H7ZW:CG3X:LDJF:5MWA:XOE6:AYGJ:4DEE:Z5JD:7QGK:554M
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

```
[root@docker3 etc]# sudo docker pull tiredofit/traefik-cloudflare-companion
Using default tag: latest
latest: Pulling from tiredofit/traefik-cloudflare-companion
213ec9aee27d: Pull complete 
309f922759ec: Extracting [==================================================>]  46.13MB/46.13MB
45d9207b0216: Download complete 
af2e2319950c: Download complete 
18e4eeca72f6: Download complete 
failed to register layer: ApplyLayer exit status 1 stdout:  stderr: lchown /run/fail2ban: invalid argument 
```

### Environment

- Image version / tag:  Latest (6.8.5)
- Guest OS: Almalinux 8.6
- Host OS: Proxmox 7.2-7

    
Upon further inspection, you are most likely assigning the group id for fail2ban far too close to the maximum GID for rootless mode. I would suggest bringing down the GID significantly from where it is right now (65500).

**Comment by mariaWitch** [comment]
Adding on to this, I have been able to narrow down to it being specifically effecting all of your Alpine base images 3.5 and above. (3.3 and 3.4 pulled fine.)

**Comment by mariaWitch** [comment]
I also just recently tested this with the fuse storage driver in order to see if that would cause a different result. And I still recieved the same results.
Additionally, I took a look at the group id of the fail2ban group on my docker instance on my development environment and the reported group id was 65550 which is beyond the maximum gid value in an LXC environment. So if that is lowered I believe the issue should be resolved.

**Comment by tiredofit** [comment]
Thanks for this - Not sure what I was thinking going over that limit - 65535 should have been a hard stop on my end.

I've accepted your PR and tagged it as `7.7.7` - It will take a few hours to build and then we'll start the build process on all the dependent images.
